/* https://fontawesome.com/docs/web/use-with/vue/add-icons */
import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faArrowRight,
  faBars,
  faCalendarDays,
  // faDatabase,
  // faGear,
  // faGears,
  faHouse,
  faLayerGroup,
  // faLocationDot,
  // faMagnifyingGlass,
  faPencil,
  faPerson,
  faPlayCircle,
  // faRecycle,
  faRightFromBracket,
  faSpinner,
  faTimes,
  faTrashCan,
  faTrophy,
  faUsers,
} from '@fortawesome/free-solid-svg-icons'
import { faGoogle } from '@fortawesome/free-brands-svg-icons'

library.add(
  faArrowRight,
  faBars,
  faCalendarDays,
  // faDatabase,
  // faGear,
  // faGears,
  faGoogle,
  faHouse,
  faLayerGroup,
  // faLocationDot,
  // faMagnifyingGlass,
  faPencil,
  faPerson,
  faPlayCircle,
  // faRecycle,
  faRightFromBracket,
  faSpinner,
  faTimes,
  faTrashCan,
  faTrophy,
  faUsers,
)
